language: c
sudo: required
compiler:
  - gcc
dist: xenial
before_install:
  - sudo apt update -q

addons:
  apt:
    packages:
      - autoconf
      - automake
      - libmosquitto-dev
      - libconfuse-dev
      - check

before_script:
  - ./build-uncrustify.sh

script:
  - ./autogen.sh
  - ./configure
  - make
  - make check
  - git diff
  - ./uncrustify.sh && git diff --exit-code
